import Head from "next/head";
import product from "../models/product";
import type { HomeProps } from "common";
import category from "../models/category";
import { Fragment, ReactElement } from "react";
import type { NextPageWithLayout } from "next";
import MainLayout from "../components/layouts/MainLayout";
import MainBanner from "../components/page/home/MainBanner";
import CtaSection from "../components/page/home/CtaSection";
import MixedStatus from "../components/page/home/MixedStatus";
import BannerPromo from "../components/page/home/BannerPromo";
import BrandSection from "../components/page/home/BrandSection";
import PromoSection from "../components/page/home/PromoSection";
import NewItemSection from "../components/page/home/NewItemSection";
import CategorySection from "../components/page/home/CategorySection";
import FeaturedSection from "../components/page/home/FeaturedSection";
import TestimonialSection from "../components/page/home/TestimonialSection";
import ProductSaleSection from "../components/page/home/ProductSaleSection";

const Home: NextPageWithLayout<HomeProps> = (props) => {
	const { categories, sales, featured, latest, mostLiked } = props;
	return (
		<Fragment>
			<Head>
				<title>Origin: Your local shopping companion</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* MAin Banner */}
			<MainBanner />
			{/* Category Section */}
			<CategorySection categories={categories} />
			{/* Sale Section */}
			<ProductSaleSection products={sales} />
			{/* Call To Action */}
			<CtaSection />
			{/* Featured Section */}
			<FeaturedSection products={featured} />
			{/* Promo Countdown */}
			<PromoSection />
			{/* New Products Section */}
			<NewItemSection products={latest} />
			{/* Promotion Banner */}
			<BannerPromo />
			{/* Mixed Product Status */}
			<MixedStatus sales={sales} features={featured} mostLiked={mostLiked} />
			{/* Brand slider */}
			<BrandSection />
			{/* Testimonial */}
			<TestimonialSection />
		</Fragment>
	);
};

Home.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;

export default Home;

export const getStaticProps = async () => {
	const categories = JSON.parse(JSON.stringify(await category.all()));
	const sales = JSON.parse(JSON.stringify(await product.onSale(10)));
	const featured = JSON.parse(JSON.stringify(await product.featured(10)));
	const latest = JSON.parse(JSON.stringify(await product.latest(10)));
	const mostLiked = JSON.parse(JSON.stringify(await product.mostLiked(10)));
	return {
		props: {
			categories,
			sales,
			featured,
			latest,
			mostLiked,
		},
		revalidate: 60,
	};
};
