import type { NextPageWithLayout } from "next";
import { Fragment, ReactElement } from "react";
import Head from "next/head";
import MainBanner from "../components/page/home/MainBanner";
import CategorySection from "../components/page/home/CategorySection";
import ProductSaleSection from "../components/page/home/ProductSaleSection";
import CtaSection from "../components/page/home/CtaSection";
import FeaturedSection from "../components/page/home/FeaturedSection";
import PromoSection from "../components/page/home/PromoSection";
import NewItemSection from "../components/page/home/NewItemSection";
import BannerPromo from "../components/page/home/BannerPromo";
import MixedStatus from "../components/page/home/MixedStatus";
import BrandSection from "../components/page/home/BrandSection";
import TestimonialSection from "../components/page/home/TestimonialSection";
import MainLayout from "../components/layouts/MainLayout";

const Home: NextPageWithLayout = () => {
	return (
		<Fragment>
			<Head>
				<title>Origin: Your local shopping companion</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* MAin Banner */}
			<MainBanner />
			{/* Category Section */}
			<CategorySection />
			{/* Sale Section */}
			<ProductSaleSection />
			{/* Call To Action */}
			<CtaSection />
			{/* Featured Section */}
			<FeaturedSection />
			{/* Promo Countdown */}
			<PromoSection />
			{/* New Products Section */}
			<NewItemSection />
			{/* Promotion Banner */}
			<BannerPromo />
			{/* Mixed Product Status */}
			<MixedStatus />
			{/* Brand slider */}
			<BrandSection />
			{/* Testimonial */}
			<TestimonialSection />
		</Fragment>
	);
};

Home.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;

export default Home;
